export const SHOW_LOADER = "APP/SHOW_LOADER";
export const HIDE_LOADER = "APP/HIDE_LOADER";
export const FOUNDED_FILM = "FILMS/FOUNDED_FILM";
export const SEARCH_FILM = "FILMS/SEARCH_FILM";
export const CLEAR_FILM = "FILMS/CLEAR_FILM";
export const SHOW_ERROR = "APP/SHOW_ERROR";
